oro_menu_config:
    items:
        desk_tab:
            label: 'Desk'
            uri: '#'
            extras:
                position: 100

        diamante_branch_list:
            label: 'Branches'
            route: diamante_branch_list
            extras:
                routes: ['diamante_branch_*']
        diamante_ticket_list:
            label: 'All Tickets'
            route: diamante_ticket_list
            extras:
                routes: ['diamante_ticket_*', 'diamante_comment_*']

        #reports
        diamante_report_list:
            label: 'Reports'
            uri: '#'

        diamante_report_tickets_by_priority:
            label: 'Tickets By priority'
            route: diamante_report_view
            routeParameters:
                id: 'tickets_by_priority'
            extras:
                routes: ['diamante_report_*']

        diamante_report_time_of_response:
            label: 'Time Of Response'
            route: diamante_report_view
            routeParameters:
                id: 'time_of_response'
            extras:
                routes: ['diamante_report_*']

        diamante_report_tickets_by_channels:
            label: 'Tickets by Channels'
            route: diamante_report_view
            routeParameters:
                id: 'tickets_by_channels'
            extras:
                routes: ['diamante_report_*']

        diamante_report_tickets_by_branch:
            label: 'Tickets by Branch'
            route: diamante_report_view
            routeParameters:
                id: 'tickets_by_branch'
            extras:
                routes: ['diamante_report_*']

        diamante_report_tickets_timeline:
            label: 'Tickets TimeLine'
            route: diamante_report_view
            routeParameters:
                id: 'tickets_timeline'
            extras:
                routes: ['diamante_report_*']

    tree:
        application_menu:
            children:
                desk_tab:
                    children:
                        diamante_branch_list: ~
                        diamante_ticket_list: ~
                        diamante_report_list:
                            children:
                                diamante_report_tickets_by_priority: ~
                                diamante_report_time_of_response: ~
                                diamante_report_tickets_by_channels: ~
                                diamante_report_tickets_by_branch: ~
                                diamante_report_tickets_timeline: ~

oro_titles:
    diamante_branch_list: ~
    diamante_branch_view: '%%branch.name%%'
    diamante_branch_create: 'Create Branch'
    diamante_branch_update: '%%branch.name%% - Edit'

    diamante_comment_create: 'Add Comment - %%ticket.subject%%'
    diamante_comment_update: 'Edit Comment - %%ticket.subject%%'

    diamante_ticket_list: ~
    diamante_ticket_view: '[%%ticket.key%%] %%ticket.subject%%'
    diamante_ticket_create: 'Create Ticket'
    diamante_ticket_update: '%%ticket.subject%% - Edit'
    diamante_ticket_create_attach: 'Add Attachment'
