placeholders:
    view_content_data_additional_information:
        items:
            diamante_contact_ticket_grid: ~
            diamante_account_ticket_grid: ~

items:
    diamante_contact_ticket_grid:
        template: DiamanteOroCRMIntegrationBundle:Contact:Grid.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_contact.entity.class%)
    diamante_account_ticket_grid:
        template: DiamanteOroCRMIntegrationBundle:Account:Grid.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_account.account.entity.class%)